// var data = {
  //   dia: " 8 ",
  //   mes: " Agosto ",
  //   dia_update: "8 de Ago",
  //   cant_positivos: "2295",
  //   inc_positivos: "+50",
  //   cant_activos: "528",
  //   inc_activos: "+19",
  //   cant_defunciones: "281",
  //   inc_defunciones: "+4",
  //   cant_sospechosos: "176",
  //   inc_sospechosos: "-2",
  //   cant_recuperados: "1512",
  //   inc_recuperados: "+27",
  //   tasa_letalidad: "12.24 %",
  //   inc_letalidad: "-0.09",
  //   cant_camas: "38 %",
  //   inc_camas: "-5 %",
  //   municipio_mas_positivos: "N/D",
  //   semaforo: "ROJO",
  //   prom_defunciones: "3.5",
  //   prom_acumulados: "29.38",
  //   prom_recuperados: "19.81",
  //   chart_acumulados_title: " Casos positivos acumulados. Para el día de hoy: ",
  //   chart_letalidad_title: "Tasa de letalidad en casos positivos acumulados. Para el día de hoy: ",
  //   chart_recuperados_title: "Promedio de personas recuperadas diariamente: ",
  //   chart_defunciones_title: "Promedio de defunciones diarias: ",
  //   chart_positivos_title: "Promedio de casos positivos acumulados por día: ",
  //   defunciones_title: " Defunciones ",
  //   camas_title: "** Camas disponibles al ",

  //   cant_defunciones_MZO: "0",
  //   inc_defunciones_MZO: "+0",
  //   porc_defunciones_MZO: "0",
  //   porc_width_def_MZO: "width: 0%",
  //   value_now_def_MZO: "0",

  //   cant_defunciones_TEC: "64",
  //   inc_defunciones_TEC: "+1",
  //   porc_defunciones_TEC: "25.00",
  //   porc_width_def_TEC: "width: 25%",
  //   value_now_def_TEC: "25",

  //   cant_defunciones_VILLA: "0",
  //   inc_defunciones_VILLA: "+0",
  //   porc_defunciones_VILLA: "0",
  //   porc_width_def_VILLA: "width: 0%",
  //   value_now_def_VILLA: "0",

  //   cant_defunciones_COL: "40",
  //   inc_defunciones_COL: "+2",
  //   porc_defunciones_COL: "50.00",
  //   porc_width_def_COL: "width: 50%",
  //   value_now_def_COL: "50",

  //   cant_defunciones_CUA: "0",
  //   inc_defunciones_CUA: "+0",
  //   porc_defunciones_CUA: "0",
  //   porc_width_def_CUA: "width: 0%",
  //   value_now_def_CUA: "0",

  //   cant_defunciones_ARM: "9",
  //   inc_defunciones_ARM: "+1",
  //   porc_defunciones_ARM: "25.00",
  //   porc_width_def_ARM: "width: 25%",
  //   value_now_def_ARM: "25",

  //   cant_defunciones_COQ: "0",
  //   inc_defunciones_COQ: "+0",
  //   porc_defunciones_COQ: "0",
  //   porc_width_def_COQ: "width: 0%",
  //   value_now_def_COQ: "0",

  //   cant_defunciones_MIN: "0",
  //   inc_defunciones_MIN: "+0",
  //   porc_defunciones_MIN: "0",
  //   porc_width_def_MIN: "width: 0%",
  //   value_now_def_MIN: "0",

  //   cant_defunciones_IXT: "0",
  //   inc_defunciones_IXT: "+0",
  //   porc_defunciones_IXT: "0",
  //   porc_width_def_IXT: "width: 0%",
  //   value_now_def_IXT: "0",

  //   cant_defunciones_COM: "0",
  //   inc_defunciones_COM: "+0",
  //   porc_defunciones_COM: "0",
  //   porc_width_def_COM: "width: 0%",
  //   value_now_def_COM: "0",

  //   activos_title: " Casos activos ",

  //   cant_activos_MZO: "150",
  //   inc_activos_MZO: "+7",
  //   porc_activos_MZO: "28.41",
  //   porc_width_act_MZO: "width: 28%",
  //   value_now_act_MZO: "28",

  //   cant_activos_TEC: "99",
  //   inc_activos_TEC: "+2",
  //   porc_activos_TEC: "18.75",
  //   porc_width_act_TEC: "width: 19%",
  //   value_now_act_TEC: "19",

  //   cant_activos_VILLA: "106",
  //   inc_activos_VILLA: "+6",
  //   porc_activos_VILLA: "20.08",
  //   porc_width_act_VILLA: "width: 20%",
  //   value_now_act_VILLA: "20",

  //   cant_activos_COL: "135",
  //   inc_activos_COL: "+3",
  //   porc_activos_COL: "25.57",
  //   porc_width_act_COL: "width: 26%",
  //   value_now_act_COL: "26",

  //   cant_activos_CUA: "10",
  //   inc_activos_CUA: "+2",
  //   porc_activos_CUA: "1.89",
  //   porc_width_act_CUA: "width: 2%",
  //   value_now_act_CUA: "2",

  //   cant_activos_ARM: "8",
  //   inc_activos_ARM: "-1",
  //   porc_activos_ARM: "1.52",
  //   porc_width_act_ARM: "width: 2%",
  //   value_now_act_ARM: "2",

  //   cant_activos_COQ: "11",
  //   inc_activos_COQ: "+0",
  //   porc_activos_COQ: "2.08",
  //   porc_width_act_COQ: "width: 2%",
  //   value_now_act_COQ: "2",

  //   cant_activos_MIN: "3",
  //   inc_activos_MIN: "+1",
  //   porc_activos_MIN: "0.57",
  //   porc_width_act_MIN: "width: 1%",
  //   value_now_act_MIN: "1",

  //   cant_activos_IXT: "1",
  //   inc_activos_IXT: "-1",
  //   porc_activos_IXT: "0.19",
  //   porc_width_act_IXT: "width: 1%",
  //   value_now_act_IXT: "1",

  //   cant_activos_COM: "5",
  //   inc_activos_COM: "+0",
  //   porc_activos_COM: "0.95",
  //   porc_width_act_COM: "width: 1%",
  //   value_now_act_COM: "1",

  //   positivos_title: "Total de casos positivos acumulados por municipio, para el día de hoy ",
  //   cant_positivos_MZO: "0",
  //   inc_positivos_MZO: "+0",
  //   porc_positivos_MZO: "0",
  //   porc_width_pos_MZO: "width: 0%",
  //   value_now_pos_MZO: "0",

  //   cant_positivos_TEC: "0",
  //   inc_positivos_TEC: "+0",
  //   porc_positivos_TEC: "0",
  //   porc_width_pos_TEC: "width: 0%",
  //   value_now_pos_TEC: "0",

  //   cant_positivos_VILLA: "0",
  //   inc_positivos_VILLA: "+0",
  //   porc_positivos_VILLA: "0",
  //   porc_width_pos_VILLA: "width: 0%",
  //   value_now_pos_VILLA: "0",

  //   cant_positivos_COL: "0",
  //   inc_positivos_COL: "+0",
  //   porc_positivos_COL: "00",
  //   porc_width_pos_COL: "width: 0%",
  //   value_now_pos_COL: "0",

  //   cant_positivos_CUA: "0",
  //   inc_positivos_CUA: "+0",
  //   porc_positivos_CUA: "0",
  //   porc_width_pos_CUA: "width: 0%",
  //   value_now_pos_CUA: "0",

  //   cant_positivos_ARM: "0",
  //   inc_positivos_ARM: "+0",
  //   porc_positivos_ARM: "0",
  //   porc_width_pos_ARM: "width: 0%",
  //   value_now_pos_ARM: "0",

  //   cant_positivos_COQ: "0",
  //   inc_positivos_COQ: "+",
  //   porc_positivos_COQ: "0",
  //   porc_width_pos_COQ: "width: 0%",
  //   value_now_pos_COQ: "0",

  //   cant_positivos_MIN: "0",
  //   inc_positivos_MIN: "+0",
  //   porc_positivos_MIN: "0",
  //   porc_width_pos_MIN: "width: 0%",
  //   value_now_pos_MIN: "0",

  //   cant_positivos_IXT: "0",
  //   inc_positivos_IXT: "+0",
  //   porc_positivos_IXT: "0",
  //   porc_width_pos_IXT: "width: 0%",
  //   value_now_pos_IXT: "0",

  //   cant_positivos_COM: "0",
  //   inc_positivos_COM: "+0",
  //   porc_positivos_COM: "0",
  //   porc_width_pos_COM: "width: 0%",
  //   value_now_pos_COM: "0",
  //   url_youtube: "https://www.youtube.com/watch?v=jBRVquQSNIE",
  //   url_reporte: "http://saludcolima.gob.mx/coronavirus/reportes/Reporte-Covid19-Colima-070820.pdf"

  // }